apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-tap
spec:
  source:
    git:
      url: https://github.com/albertovmware/tanzu-webapp-tap
      ref:
        branch: main
